export const config = {
    api: {
        path: {
            login: '/login',
            logout: '/logout',
            attachment: {
                find: '/attachment/find',
                upload: '/attachment/upload',
                download: '/attachment/download',
                delete: '/attachment/delete/',
            },
            user: {
                findAll: '/user',
                findById: '/user/id/',
                findByRole: '/user/role/',
                findAllRoles: '/user/roles',
                add: '/user/add',
                update: '/user/update',
                updatePassword: '/user/update-password',
                uploadProfileImage: '/user/upload-profile-image',
                deleteUser: '/user/delete',
            },
            contacts: {
                baseUrl: '/contact',
                find: '/find',
                count: '/count',
                paramsFide: '/params-fide',
                call: '/call',
                contactNumberFide: '/contact-number',
                findEmailByContact: '/contact-email',
            },
            call: {
                url: '/call',
                count: '/count',
                caseTopic: '/casetopic',
                organizations: '/organizations',
                contacts: '/allcontact',
                caseSubjects: '/casesubjects',
                channels: '/channels',
                countcontact: '/call-contact/count/',
                contactbypage: '/contactbypage',
                contactid: '/contacts',
                activitiesType: '/activitiestype',
                uploadFile: '/upload',
                createActivityTopic: '/activityTopic',
                callById: '/call-id',
                caseById: '/case-id',
                contactNumberById: '/contacts-number',
                emailById: '/email-id',
                allStatus: '/all-status',
            },
            report: {
                channelByAgent: '/report/channelByAgent',
                caseTypeByAgent: '/report/caseTypeByAgent',
                summaryByMonth: '/report/summaryByMonth',
                caseDetail: '/report/caseDetail',
                getAgent: '/report/getAgent',
            },
            callList: {
              baseUrl: '/case',
              status: '/status',
              },
        },
    },
    strapi: {
        url: 'https://devel.convtech.dev/qcrm-strapi/api',
        path: {
            auditlog: '/auditlogs',
        },
        key: '8c8cb1eb42112e450ac048f4e70878e4becdfc27544d14a8b65c942b9a9fab9333596d26aeedeeb1b65322ffe5e380eee7fe8d1b61c91d0f2427b972015f744c35ebd634f4d28cdd750dd2fd37088173eb7cf85d615ff6dacaa1eec1dfa87b751590302093fed23336e67691e8afb78032e9cf19b4e169a04faeb481b8d612a7',
    },
    file: {
        maxSize: 2 * 1024 * 1024,
        type: '.xlsx',
    },
    roleCanAccessCUDForm: ['admin', 'system', 'super admin'],
    urlWebSocket: {
        urlQAgent: `ws://127.0.0.1:8748/QAgent`,
    },
};
