export const config = {
    api: {
        path: {
            login: '/login',
            logout: '/logout',
            attachment: {
                upload: '/attachment/upload',
                delete: '/attachment/delete/',
            },
            user: {
                findAll: '/user',
                findById: '/user/id/',
                findAllRoles: '/user/roles',
                add: '/user/add',
                update: '/user/update',
                updatePassword: '/user/update-password',
                uploadProfileImage: '/user/upload-profile-image',
                deleteUser: '/user/delete',
            },
            contacts: {
                baseUrl: '/contact',
                find: '/find',
                count: '/count',
                countByAssignedUserId: '/count-by-assigned-user-id',
                paramsFide: '/params-fide',
                call: '/call',
                contactNumberIdByPhone: '/contact-number-id',
                contactGroup: '/contact-group',
                contactChatId: '/contact-chat',
                updateContactNumbers: '/numbers',
                organization: '/organization',
            },
            call: {
                url: '/call',
                uploadFile: '/upload',
            },
            report: {
                baseUrl: '/report',
                list: '/list',
            },
            callList: {
                baseUrl: '/case',
                all: '/all',
                status: '/status',
                channels: '/channels',
                agent: '/agent',
                comment: '/comments',
                callStatus: '/call-status',
                callStatusId: '/call-status-id',
                history: '/history',
                casePriority: '/case-priority',
                casePriorityOverDue: '/case-priority-overdue',
                inspectionCompany: '/inspection-company',
                inspectionCompanyById: '/inspection-company/case',
                inspectionCompanySendReply: '/inspection-company-send-reply',
                caseGroupReport: '/case-group-report',
            },
            chatHistory: '/chathistory/getchat',
        },
    },
    file: {
        maxSize: 2 * 1024 * 1024,
        type: '.xlsx',
    },
    roleCanAccessCUDForm: ['admin', 'system'],
    operationType: {
        inbound: 'Inbound',
        outbound: 'Outbound',
    },
};
