export const config = {
    api: {
        path: {
            login: '/login',
            logout: '/logout',
            attachment: {
                find: '/attachment/find',
                upload: '/attachment/upload',
                download: '/attachment/download',
                delete: '/attachment/delete/',
            },
            user: {
                findAll: '/user',
                findById: '/user/id/',
                findByRole: '/user/role/',
                findByGroup: '/user/group/',
                findAllRoles: '/user/roles',
                findAllGroups: '/user/groups',
                add: '/user/add',
                addGroup: '/user/add-group',
                update: '/user/update',
                updateGroup: '/user/update-group',
                updatePassword: '/user/update-password',
                uploadProfileImage: '/user/upload-profile-image',
                deleteUser: '/user/delete',
                deleteGroup: '/user/delete-group/',
            },
            announcement: {
                findAll: '/announcement',
                findById: '/announcement/id/',
                findByDate: '/announcement/date/',
                add: '/announcement/add',
                update: '/announcement/update',
                delete: '/announcement/delete/',
            },
            calendarEvent: {
                findAll: '/calendar-event',
                findById: '/calendar-event/id/',
                findByDate: '/calendar-event/date',
                findByMonth: '/calendar-event/month/',
                findByMember: '/calendar-event/member/id/',
                findByTagId: '/calendar-event/tag/',
                add: '/calendar-event/add',
                addTag: '/calendar-event/add-tag',
                update: '/calendar-event/update',
                updateTag: '/calendar-event/update-tag',
                delete: '/calendar-event/delete',
                deleteTag: '/calendar-event/delete-tag',
                findAlltags: '/calendar-event/tags',
            },
            elearning: '/e-learning',
            surveyForm: {
                baseUrl: '/survey-form',
                find: '/find',
                count: '/count',
            },
            contacts: {
                baseUrl: '/contact',
                find: '/find',
                count: '/count',
                paramsFide: '/params-fide',
                surveyForm: '/survey-form',
                call: '/call',
            },
            call: {
                url: '/call',
                count: '/count',
                caseTopic: '/casetopic',
                organizations: '/organizations',
                contacts: '/allcontact',
            },
            survey: {
                baseUrl: '/survey',
                existing: '/existing',
            },
            notification: {
                findNotification: '/notification',
                findNotificationUnReadByUserId: '/notification/unread/',
                findNotificationReadByUserId: '/notification/read/',
                readAllNotificationByUserId: '/notification/read-all/',
            },
        },
    },
        strapi: {
        url: 'http://localhost:1337/api',
        path: {
            auditlog: '/auditlogs',
        },
        key: 'b41becc9e75e14f53e6c7f6c84f9f53bc7419e6390ce3c85be6a3c4ff9b56befe4a95a9fcfc34f270694737f8660e0f9f7cfffa5e2ed2dc707b65b310e07b3aa781c93eed5c78eabbbac448a6095017fc0aa8e65c703a8883f9cf118cd06b2aa5810d9e23d73d5e5208a9e18341dcd0f77b8b2d8104839e98e3cadc22fc3b624',
    },
    file: {
        maxSize: 2 * 1024 * 1024,
        type: '.xlsx',
    },
    roleCanAccessCUDForm: ['admin', 'system', 'super admin'],
};
