export const report = {
    summary: {
        date: 'วันที่',
        HotIn: 'Hotline (Inbound)',
        HotOut: 'Hotline (Outbound)',
        MailIn: 'Email (Inbound)',
        MailOut: 'Email (Outbound) ',
        Mobile: 'Mobile Unit',
        LiveChat: 'Live Chat',
        Other: 'อื่นๆ',
        TotalChannel: 'รวม (ช่องทาง)',
        Topic1: 'ข้อมูลทั่วไป',
        Topic2: 'ระบบ Drive',
        Topic3: 'E-Academy',
        Topic4: 'ติดต่อประสานงาน',
        Topic5: 'ประชาสัมพันธ์และติดตามผล',
        Topic7: 'ร้องเรียน',
        Topic8: 'ชมเชย',
        Topic6: 'อื่นๆ',
        TotalTopic: 'รวม (Case Type)',
    },
    channel: {
        username: 'เจ้าหน้าที่',
        HotIn: 'Hotline (Inbound)',
        HotOut: 'Hotline (Outbound)',
        MailIn: 'Email (Inbound)',
        MailOut: 'Email (Outbound) ',
        Mobile: 'Mobile Unit',
        LiveChat: 'Live Chat',
        Other: 'อื่นๆ',
        Total: 'รวม',
    },
    cases: {
        caseId: 'ID',
        channel: 'ช่องทาง',
        contact: 'ผู้ติดต่อ',
        org: 'ร้านค้า/บริษัท',
        contacttype: 'ประเภทผู้ประกอบการ',
        email: 'อีเมล์',
        caller: 'เบอร์ติดต่อ',
        activityname: 'ประเภทกิจกรรม',
        casetype: 'หัวข้อที่ติดต่อ',
        casesub: 'เรื่องที่ติดต่อ',
        description: 'รายละเอียด',
        solution: 'แนวทางแนะนำ/แก้ไข',
        agent: 'เจ้าหน้าที่',
        province: 'จังหวัด',
        created: 'วันที่สร้าง',
        type: 'ประเภท',
    },
    topic: {
        username: 'เจ้าหน้าที่',
        HotIn: 'Hotline (Inbound)',
        HotOut: 'Hotline (Outbound)',
        MailIn: 'Email (Inbound)',
        MailOut: 'Email (Outbound) ',
        Mobile: 'Mobile Unit',
        LiveChat: 'Live Chat',
        Other: 'อื่นๆ',
        TotalChannel: 'รวม (ช่องทาง)',
        Topic1: 'ข้อมูลทั่วไป',
        Topic2: 'ระบบ Drive',
        Topic3: 'E-Academy',
        Topic4: 'ติดต่อประสานงาน',
        Topic5: 'ประชาสัมพันธ์และติดตามผล',
        Topic7: 'ร้องเรียน',
        Topic8: 'ชมเชย',
        Topic6: 'อื่นๆ',
        TotalTopic: 'รวม (หัวข้อที่ติดต่อ)',
        Sub1: 'แนะนำโครงการ ฝึกอบรม/สัมนา',
        Sub2: 'กำหนดการรายละเอียดการจัดโครงการ',
        Sub3: 'เนื้อหาหลักสูตร/การฝึกอบรมของแต่ละโครงการ/หลักสูตร',
        Sub4: 'การต่อยอดกิจกรรมกรมและหน่วยงานอื่น',
        Sub5: 'ขอเอกสารเพิ่มเติมทางแฟกซ์หรือทางอีเมล',
        Sub6: 'สอบถามวิธีการสมัครเช้าร่วมโครงการ/การชำระเงินผ่านระบบ Drive',
        Sub7: 'ติดตามสถานะการสมัคร',
        Sub8: 'เพิ่ม/ยกเลิก/แก้ไข สถานะการสมัคร',
        Sub9: 'แก้ไขข้อมูลในฐานระบบ',
        Sub10: 'ลืมรหัสผ่านระบบ Drive',
        Sub11: 'ปัญหาการใช้งานระบบ Drive',
        Sub12: 'การชำระเงินผ่านระบบ Drive',
        Sub13: 'แนะนำโครงการ E-Academy',
        Sub14: 'สอบถามวิธีการสมัครเข้าเรียนหลักสูตร',
        Sub15: 'ลืมรหัสผ่าน E-Academy',
        Sub16: 'ขอประกาศนียบัตร',
        Sub17: 'ปัญหาการเข้าใช้งานเว็บไซต์ E-Academy',
        Sub18: 'ติดต่อส่วนงานอื่นๆของสถาบัน NEA',
        Sub19: 'ติดต่อหน่วยงานอื่นของกรมฯ',
        Sub20: 'สอบถามกิจกรรมอื่นๆของกรม',
        Sub21: 'ประชาสัมพันธ์โครงการ/หลักสูตร',
        Sub22: 'ติดตามและประเมินผล',
        Sub23: 'ทดสอบระบบ',
        Sub24: 'โทรผิด',
        Sub25: 'เสียงเงียบ',
        Sub26: 'ก่อกวน',
        Sub27: 'สายหลุด',
        Sub28: 'เจ้าหน้าที่ตอบกลับทางอีเมล',
        TotalSub: 'รวม (เรื่องที่ติดต่อ)',
    },
    survey: {
        date: 'Date',
        email: 'Email',
        contactName: 'Contact Name',
        successSend: 'Success Send',
        errorSend: 'Error Send',
        successResend: 'Success Resend',
        errorResend: 'Error Resend',
        surveyName: 'Evaluation Form',
        agent: 'Agent',
    },
    surveySendById: {
        username: 'Agent',
        Total: 'Total Send',
        TotalSend: 'Send',
        TotalErrorSend: 'Error Send',
        TotalReSend: 'Total Resend',
        totalErrorReSend: 'Error ReSend',
    },
    surveySendSummary: {
        createdDate: 'Send Date',
        Total: 'Total Send',
        TotalSend: 'Send',
        TotalErrorSend: 'Error Send',
        ResendDate: 'Resend Date',
        TotalReSend: 'Total Resend',
        totalErrorReSend: 'Error ReSend',
    },
};
