export const report = {
    summary: {
        date: 'วันที่',
        HotIn: 'Hotline (Inbound)',
        HotOut: 'Hotline (Outbound)',
        MailIn: 'Email (Inbound)',
        MailOut: 'Email (Outbound) ',
        Mobile: 'Mobile Unit',
        LiveChat: 'Live Chat',
        Other: 'อื่นๆ',
        TotalChannel: 'รวม (Channel)',
        Topic1: 'ข้อมูลทั่วไป',
        Topic2: 'ระบบ Drive',
        Topic3: 'E-Academy',
        Topic4: 'ติดต่อประสานงาน',
        Topic5: 'ประชาสัมพันธ์และติดตามผล',
        Topic7: 'ร้องเรียน',
        Topic8: 'ชมเชย',
        Topic6: 'อื่นๆ',
        TotalTopic: 'รวม (Case Type)',
    },
    channel: {
        username: 'Agent Name',
        HotIn: 'Hotline (Inbound)',
        HotOut: 'Hotline (Outbound)',
        MailIn: 'Email (Inbound)',
        MailOut: 'Email (Outbound) ',
        Mobile: 'Mobile Unit',
        LiveChat: 'Live Chat',
        Other: 'อื่นๆ',
        Total: 'รวม',
    },
    topic: {
        username: 'Agent Name',
        Topic1: 'ข้อมูลทั่วไป',
        Topic2: 'ระบบ Drive',
        Topic3: 'E-Academy',
        Topic4: 'ติดต่อประสานงาน',
        Topic5: 'ประชาสัมพันธ์และติดตามผล',
        Topic7: 'ร้องเรียน',
        Topic8: 'ชมเชย',
        Topic6: 'อื่นๆ',
        Total: 'รวม ',
    },
};
